= Layered Standard for Structured Data
:sectnums:
:sectnumlevels: 5
:toc: left
:toc-title: Contents
:toclevels: 5
:xrefstyle: short
:docinfo: shared
:docinfodir: docs
:stylesheet: fmi-spec.css
:stem: latexmath
:source-highlighter: highlightjs
:nofooter:
:favicon: images/favicon.ico
:revdate: unreleased
:revnumber: 1.0
:icons: font

ToDo: has to concentrate more on lookup tables

Based on FMI 3.0, this layered standard defines how variables (especially parameters) of an FMU can be structured and grouped in a more flexible way than with the "structured naming convention" of the FMI Standard (version 1.0, 2.0, 3.0).
Additionially it defines special semantics to certain parameter groups in order to describe regular maps.

{empty} +
{empty}

Copyright (C) 2012-2024 The Modelica Association Project FMI.

This document is licensed under the Attribution-ShareAlike 4.0 International license.
The code is released under the 2-Clause BSD License.
The licenses text can be found in the https://raw.githubusercontent.com/modelica/fmi-standard/master/LICENSE.txt[LICENSE.txt] file that accompanies this distribution.

{empty}

== Introduction

=== Motivation 

For many use cases grouping of several variables (especially parmaters) is benefical. 
A very important application is the definition of maps defined on rectilinear grids,  through several array variables, which requires additional semantics.
E.g., CombiTable1D or CombiTable2D blocks of the Modelica standard library used within an FMU can be exposed with this approach.

This layered standards enables these features based on the concept of Terminals from the FMI Standard of FMI 3.0.

=== How to Read This Document

The standard document is in HTML allowing use of in-document links.
By pressing "t", the table of contents can be displayed on the left side or hidden.

In key parts of this document, non-normative examples are used to help understand the standard.

Conventions used in this document:

* Non-normative text is given in square brackets in italic font: _[Especially examples are defined in this style.]_

* The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in https://tools.ietf.org/html/rfc2119[RFC 2119] (regardless of formatting and capitalization).

=== Rough Outline of the Approach

FMI 3.0 https://fmi-standard.org/docs/3.0/#fmiTerminalsAndIcons[Terminals] are used to define groups of variables, especially parameters.

A special kind of parameter group defines maps on rectilinear grids (with additional semantic meaning).

== Layered Standard Manifest File

The manifst file signals to the importer that the FMU supports this layered standard and enables the interpretation of the `TerminalsAndIcons.xml` file in the intended way.

<<table-schema-fmi-ls-struct-attributes>> shows the content of `fmi-ls-manifest.xml`.

.`fmiLayeredStandardManifest` attribute details.
[[table-schema-fmi-ls-struct-attributes]]
[cols="1,1,1,2",options="header"]
|====
|Attribute
|Namespace
|Value
|Description

|`fmi-ls-name`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `org.fmi-standard.fmi-ls-struct`
| Name of the layered standard in reverse domain name notation.

|`fmi-ls-version`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `1.0.0`
| Version of the layered standard. This layered standard uses semantic versioning, as defined in <<PW13>>.

|`fmi-ls-description`
| `\http://fmi-standard.org/fmi-ls-manifest`
| `Layered standard for structuring of variables`
| String with a brief description of the layered standard that is suitable for display to users.

|====

An example of a manifest file for this layered standard is shown below:

[source, xml]
----
include::examples/fmi_ls_struct_manifest_example.xml[]
----

[#common-concepts]
== Common concepts for the representation of maps 

===  Defintions


=== Defintion of `terminalKind`s

* TerminalKind `org.fmi-standard.fmi-ls-struct.rectilinearGridMap` for maps defined on rectilinear grids.
* TerminalKind `org.fmi-standard.fmi-ls-struct.rectilinearGridMap` for maps defined by unsructured tuples of ("point cloud").

=== `variableKinds` of terminal member variables:

We want to represent a map from a domain set to a codomain through by providing the points in the domain set and the values they are mapped to.

* `org.fmi-standard.fmi-ls-struct.domain`:: For each of the n dimensions of the domain set a 1d array variable (typically a parameter or a constant) of coordinates is provided

* `org.fmi-standard.fmi-ls-struct.domainInput`:: Optionally, for for each `domain` variable at most one array variable (typically an input or a local variable) can be referenced that represents the current operating point (along this dimension). If present must be listed directly after the corresponding domain. The domain_input isn't required to be a scalar, it could be variable with several dimensions. However the size of each domainInput must be the same for each domain: For a nonscalar inputs v=[v1,...vn], w=[w1,...wn], ... the function is evalutated elementwise and we get an output vector z=[f(v1, w1, ...), .... f(vn, wn, ...)]

* `org.fmi-standard.fmi-ls-struct.codomain`:: For each of the reprensented points in the domain set, the values to which they are mapped are represented. _[There can be multiple terminal member variables with `variablKind` `codomain` to reperenset multiple maps in one terminal.]_

* `org.fmi-standard.fmi-ls-struct.domainOutput`:: Optionally, for for each `domain` variable at most one array variable (typically an input or a local variable) can be referenced that represents calculted output value of the map. Here the order in the `TerminalsAndIcons.xml`matters: if present, a `domainOutput` variable is defined directly afte the corresponding `codomain` variable.

* Additional terminal member variables that do not fit into these categories shall not have a Variablekind starting with `org.fmi-standard.fmi-ls-struct`. 


=== Definition of Matching rules

* org.fmi-standard.fmi-ls-struct.map

Requirement for the matching: The number of domains must be the same and the terminal member names (+ variables type + size) of all domains (i.e., `variableKind=org.fmi-standard.fmi-ls-struct.domain`) must match. If all domains match, connect all these domains. Connect all codomains (`variableKind=org.fmi-standard.fmi-ls-struct.codomain`) that match. 
Don't connect any other terminal member variables.

_[This indicates that the variableKind of the member should be considered for the connection of the individual members of the terminal.]_

=== Structure of the FMU archive

This layerd standard uses and extends the "Terminals and Icons Concept" of FMI 3.0. All information is stored in the TerminalasAndIcons.xml file in the TerminalsAndIcons folder of an FMU.


==  Maps on rectilinear grid

=== Definitions

n-d Lookup tables::  In the context of this layered standard, an n-D lookup table is a sampled representation of a function of n input variables latexmath:[y=F(x_1, x_2, x_3, \dots, x_n)] sampled on the vertices of a rectlinear grid. Such an n-D lookup table could be also called a map from the n-dimensional domain to a .

_[In <<ASAM-MCD2>> a 1-d lookup table is called *CURVE*, a 2-d lookup table is called *MAP*, and a 3-d lookup table is called *CUBOID*. 4-d and 5-d lookup tables are called *CUBE_4* and \*CUBE\_5*, respectively. Higher dimensional lookup tables are not defined in <<ASAM-MCD2>>.]_

Domain:: For each of the n dimensions of the lookup table an 1d array variable (typically a parameter or a constant) with the sampling points (along this dimension) of the lookup-table must be referenced.
Codomain:: The sampled function values are stored in this n-dimensional array. There can be several codomains for the same set of domains and domain inputs.  ToDo: size of a codomain array = Producut of sized ot the domain arrays.



=== Example

[source, xml]
----
include::examples/terminalsAndIcons.xml[]
----

[source, xml]
----
include::examples/modelDescription.xml[]
----


ToDo: Add description how to handle a combitable.

==  Irregular map ("Point Cloud")


=== Definitions

Definition of domains and codomains as above

For domains x=(x_1, x_2, ... x_n), y=(y_1, y_2, ...y_n), z=(z_1, z_2, z_3, ...z_n) ... and codomain u (u_1, u_2,...u_n), v=(v_1, v_2, ... v_n), the tuples of (xi, yi, zi, ...) are mapped to  values (ui, vi, ...).

All domains and codomains must have the same lenght


ToDo add picture



== Known Limitations of This Standard

General limitations:

* todo

[bibliography]
== References

- [[[PW13]]] Preston-Werner, T. (2013): **Semantic Versioning 2.0.0**.  https://semver.org/spec/v2.0.0.html
- [[[ASAM-MCD2]]] ASAM e.V. (2018) **ASAM MCD-2 MC (aka ASAP2) v1.7.1**. https://www.asam.net/standards/detail/mcd-2-mc/


